version: 2

build:
  os: ubuntu-22.04  
  tools:
    python: "3.12"  # Specify the Python version

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .  # Specify the path to your Python package
    - method: pip
      requirements: docs/requirements.txt  # Specify a requirements file if you have one