version: 2

build:
  os: ubuntu-22.04  
  tools:
    python: "3.12.1"  


sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.12.1
  install:
    - method: pip
      path: .
    - method: pip
      extra_requirements:
        - docs