version: 2

build:
  os: ubuntu-22.04  
  tools:
    python: "3.12"  # Specify the Python version

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .  # Install your Python package from the current directory